### ISSUE TITLE
Fallo al tomar imágenes

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/GLORIA_RTSInteractiveRTS2#3]
En BOOTES 1A no puedo tomar imágenes:

![image](https://cloud.githubusercontent.com/assets/7371595/3111848/88b1f796-e6b6-11e3-9a09-449cfdb3ab7d.png)

**Comment by mclopez-uma** [comment]
El disco principal de B1A está lleno, aunque las imágenes se transfieren a otra unidad se necesita de espacio en ésta. De hecho los logs del RTI están cortados porque ya no se podía escribir más en disco.

**Comment by carlibiri** [comment]
Hemos eliminado LOGS por cantidad de 1GB y ahora tiene el disco 1GB aprox de espacio libre. Además, hemos modificado la generación de logs para que quede limitada a 500MB. Pendiente de probar esta noche.

**Comment by carlibiri** [comment]
En cuanto Mª Carmen termine esto cierra la issue.
