### ISSUE TITLE
D50 no mueve la montura ni toma imágenes

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/GLORIA_RTSInteractiveRTS2#6]
Ahora mismo estoy en la reserva y no puedo interactuar con el telescopio...

A ver qué pasa.

**Comment by mclopez-uma** [comment]
Acabo de revisar la reserva del 02/06/2014 21h00 UT y aparentemente el RTI funcionó correctamente. Tras llegar el comando de interrupción, al RTI llegaron tres bloques de operaciones equivalentes: movimiento de montura hacia objeto, lectura de estado de la montura y toma de imágenes. Todas estas operaciones se realizaron correctamente y las imágenes se encuentran en el repositorio del telescopio.

Los movimientos fueron:
- 9:05 -> Saturno: http://altamira.asu.cas.cz:8081/RTIDBRepository/FileServlet?uuid=0000000e0000000120140602000001465e6c369dv001&format=JPG
- 9:12 -> M3: http://altamira.asu.cas.cz:8081/RTIDBRepository/FileServlet?uuid=0000000e0000000120140602000001465e6e2b0ev001&format=JPG
- 9:14 -> M1: http://altamira.asu.cas.cz:8081/RTIDBRepository/FileServlet?uuid=0000000e0000000120140602000001465e6f60aev001&format=JPG

En el respositorio de imágenes de D50 hay más imágenes de la noche, supongo que de reservas posteriores.

Asigno incidencia  a Esteban: interfaz del experimento nocturno.

**Comment by angelagonzalez** [comment]
El usuario de las 21:15 dice que sí pudo tomar imágenes en la encuesta y da una nota de 7.

**Comment by carlibiri** [comment]
Alguien puede mirar qué ocurrió a las 23, cuando estaba mi reserva? No pude tomar imágenes...

**Comment by mclopez-uma** [comment]
Carlos, la he mirado yo, es la de las 21:00 UT

**Comment by carlibiri** [comment]
Esteban please, revisa esto porque las imágenes están tomadas, pero no aparecieron en el interfaz del experimento.

**Comment by esgg** [comment]
Tras un rato creo que hemos encontrado la respuesta. Esta reserva, la 4442, pertenece a otro usuario. Estabas en modo administrador, por lo que no puedes interactuar con el experimento

**Comment by carlibiri** [comment]
Pues seguro, es que a esa hora ya estaba yo un poco chof, seguramente le daría a entrar y no me daría cuenta de que no era mi reserva... Mucha gracias Esteban!! Problema resuelto.
