### ISSUE TITLE
No puedo tomar imágenes en BART

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/GLORIA_RTSInteractiveRTS2#7]
Se mueve la montura, pero no se pueden tomar imágenes, da error.

**Comment by mclopez-uma** [comment]
Por la hora del correo que enviaste, entiendo que tu reserva es la del 02/06/2014, 21:15UT, ¿es así? En esa reserva no llegaron al RTI ningún comando de exposición. 

Durante esa noche llegaron sólo tres peticiones de exposición y las tres cayeron en error. Muchas de las peticiones hechas a RTS2 devolvían: HTTP/1.1 502 Proxy Error. De hecho, ahora sigue ocurriendo. Hablaré con Jan.

**Comment by angelagonzalez** [comment]
El usuario de las 21 dice que sí pudo tomar imágenes en la encuesta y da una nota de 9.

**Comment by mclopez-uma** [comment]
¿Seguro que es en Bart y la noche del  02/06/2014? Porque en el repositorio de imágenes de Bart no hay ninguna de esa noche. De D50 sí.

**Comment by angelagonzalez** [comment]
No lo puedo asegurar pero es lo que dice el usuario en la encuesta. La rellenó a las 21:47UT de anoche, así que creo que es fiable.

**Comment by carlibiri** [comment]
Igual no marcó correctamente el telescopio... Yo no pude hacer nada, Mª Carmen please mira los logs...

**Comment by mclopez-uma** [comment]
Ya los he mirado. Sólo había 3 peticiones de toma de imágenes y fallaron las 3. En el repositorio no hay imágenes... RTS2 daba problemas de comunicación, ya he informado a Jan.

**Comment by carlibiri** [comment]
OK, veo entonces que es un problema de RTS2. Avísame cuando esté para volver a probar. Lo raro es que la montura funcionaba...

**Comment by angelagonzalez** [comment]
Carlos, sí marcó bien el telescopio, lo he comprobado con la BD de usuarios (me lo ha mandado Esteban porque yo no puedo acceder desde aquí). No entiendo lo que ocurre, ¿escribo al usuario para que confirme que tomó imágenes?

**Comment by carlibiri** [comment]
Sip, es raro...

**Comment by esgg** [comment]
He estado comprobando la BD y no hay ninguna imagen indexada en esa reserva. No se pudieron tomar imágenes, aparecía el siguiente mesaje "Error. null"

**Comment by carlibiri** [comment]
Dejo la tarea asignada a Mª Carmen, ella ha contactado con el propietario de BART porque hubo un problema de comunicaciones con RTS2 y parece que todavía existe.

**Comment by mclopez-uma** [comment]
Anoche a las 21:00 CEST recibí un correo de Jan indicando que había reiniciado los demonios afectados, me dice que intentará estar pendiente de esto  para que no vuelva a ocurrir. 
Yo acabo de comprobar que las comunicaciones con RTS2 de Bart funcionan correctamente.

Cierro la incidencia.

**Comment by angelagonzalez** [comment]
Releyendo la encuesta que rellenó el usuario, ciertamente es contradictoria, puesto que dice que cambió filtros y pudo guardar las imágenes, pero previamente contesta que no pudo tomar imágenes. De modo que ahora todo cuadra.
