### ISSUE TITLE
El 03-06-2014 a las 21:30 UT no pude entrar a la reserva nº 4503 con BOOTES-1A, el siguiente usuario sí entró

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/GLORIA_RTSInteractiveRTS2#8]
El 03-06-2014 a las 21:30 UT no pude entrar a la reserva nº 4503 con BOOTES-1A, el siguiente usuario (reserva nº 4497) sí entró y pudo tomar imágenes.

**Comment by esgg** [comment]
Mirando los logs, GLORIA entró a BOOTES-1A a las 21:40, después de unos cuantos reintentos. Desconozco el motivo de este retraso. Te daré más información en cuanto miremos las trazas del RTI.

**Comment by angelagonzalez** [comment]
Cierro esta incidencia porque ya está antigua y han ocurrido nuevas cosas después.
